# Generated by Django 5.2.8 on 2025-11-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('year_released', models.IntegerField(verbose_name='year_released')),
                ('genre', models.CharField(max_length=64, verbose_name='genre')),
                ('studio', models.CharField(max_length=64, verbose_name='studio')),
            ],
        ),
    ]
